name: "kubectl"
repository: github.com/khulnasoft-lab/vul-plugin-kubectl
version: "0.1.0"
usage: scan kubectl resources
description: |-
  A Vul plugin that scans the images of a kubernetes resource.
  Usage: vul kubectl TYPE[.VERSION][.GROUP] NAME
platforms:
  - selector: # optional
      os: darwin
      arch: amd64
    uri: ./vul-kubectl # where the execution file is (local file, http, git, etc.)
    bin: ./vul-kubectl # path to the execution file
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/khulnasoft-lab/vul-plugin-kubectl/releases/download/v0.1.0/vul-kubectl.tar.gz
    bin: ./vul-kubectl
  - selector:
      os: darwin
      arch: arm64
    uri: ./vul-kubectl
    bin: ./vul-kubectl
